## This script produces "values at risk" information

datapath <- "../../../data/"
resultpath <- "../../../results/"

do.figures <- T
do.drophighres <- F
suffix <- "-cl"
do.years <- "2005-2014" #"1995-2004"

outsuffix <- suffix
if (do.years == "2005-2009") {
    outsuffix <- paste0(outsuffix, "-2005-2009")
    fromyear <- -9
    toyear <- -5
    weights.suffix <- ""
} else if (do.years == "2010-2014") {
    outsuffix <- paste0(outsuffix, "-2010-2014")
    fromyear <- -4
    toyear <- 0
    weights.suffix <- ""
} else if (do.years == "1995-2004") {
    outsuffix <- paste0(outsuffix, "-1995-2004")
    fromyear <- -19
    toyear <- -10
    weights.suffix <- "-1995-2004"
} else if (do.years == "2005-2014") {
    fromyear <- -9
    toyear <- 0
    weights.suffix <- ""
} else {
    warning("Unknown do.years")
}

source("../lib/names.R") # this is in http://github.com/jrising/research-common
source("../lib/saufuncs.R")
source("../lib/resilience.R")
source("../food/protein.R")

## Species-specific economic values
values <- read.delim(paste0(datapath, "saudata/values.csv"), sep=",", header=F)

## Species-specific catches
catches <- read.delim(paste0(datapath, "saudata/catches.csv"), sep=",", header=F)

## EEZ to EEZ transitions
## Generated by transitions/analysis.R
transits <- read.csv(paste0(datapath, "spawn-transits/spawn-transits-rescaled", suffix, ".csv"))

## SAU and Sovereign-level weights
## Generated by country-weights.R
regions <- read.csv(paste0(datapath, "weights/combined-regions-new", weights.suffix, ".csv"))
weights <- read.csv(paste0(datapath, "weights/combined-country", weights.suffix, ".csv"))

## Mapping of species to commercial group
groups <- read.csv(paste0(datapath, "saudata/species.csv"))

## How many $USD are at risk?
results <- data.frame(sink=c(), specie=c(), value=c(), catch=c(), sourcecount=c(), selfportion=c(), totalportion=c(), sovereign=c(), resilience=c(), protein=c())
exports <- data.frame(source=c(), specie=c(), value=c(), catch=c(), isself=c(), resilience=c())
ctr <- 0
for (eez in unique(transits$sink)) {
    ctr <- ctr+1
    ## What are the values we have to choose from?
    insau <- regions$name %in% eez2sau(eez)
    regionids <- regions$country[insau]
    if (length(regionids) == 0) {
        print(c("Problem finding eez", eez))
        next
    }

    if (length(unique(regions$sovereign[insau])) > 1) {
        print(c("Multiple sovereigns within", eez))
    }

    sovereign <- unique(regions$sovereign[insau])

    myvalues <- combine.regions(values, regionids)
    mycatches <- combine.regions(catches, regionids)

    eeznum <- as.numeric(substring(regionids, 7, nchar(as.character(regionids)) - 5))
    mygroups <- subset(groups, eez %in% eeznum)

    ## Where is the value coming from?
    species <- unique(transits$species[transits$sink == eez])
    for (specie in species) {
        ## Total weight for this species
        ## From how many countries does this species come?
        sourcecount <- sum(transits$sink == eez & transits$species == specie)
        ## What portion of all this species transits come into eez?
        totalportion <- sum(transits$portion[transits$sink == eez & transits$species == specie])
        ## How much is coming also from this eez?  This will be <= totalportion
        selfportion <- sum(transits$portion[transits$source == as.character(eez) & transits$sink == eez & transits$species == specie])

        valuecatch <- species.averages.keyed(specie, mygroups, myvalues, mycatches, fromyear=fromyear, toyear=toyear)
        resilience <- get.species.resilience.level(specie)
        protein <- get.protein(specie)$protein

        results <- rbind(results, data.frame(sink=eez, specie, value=valuecatch[1], catch=valuecatch[2], sourcecount, selfportion, totalportion, sovereign, resilience, protein))

        ## Determine who exports this catch and value
        ## Want to be able to compute sum_i x_i p_ij (1 - p_ii / sum_j p_ij)
        sources <- transits$source[transits$sink == eez & transits$species == specie]
        portions <- transits$portion[transits$sink == eez & transits$species == specie]
        isself <- transits$source[transits$sink == eez & transits$species == specie] == as.character(eez)
        exports <- rbind(exports, data.frame(sink=eez, source=sources, specie, value=valuecatch[1] * portions / sum(portions), catch=valuecatch[2] * portions / sum(portions), isself, resilience))
    }
}

## Show how exports compare across depth/distance
if (do.figures) {
    library(dplyr)
    exports2 <- exports[!exports$isself,] %>% group_by(specie) %>% summarize(value=sum(value, na.rm=T), catch=sum(catch, na.rm=T))
    depths <- read.csv(paste0(datapath, "spawn/depths.csv"))
    exports2 <- exports2 %>% left_join(depths, by=c('specie'='scientific'))
    landdists <- read.csv(paste0(datapath, "spawn/landdists.csv"))
    exports2 <- exports2 %>% left_join(landdists, by=c('specie'='scientific'))

    library(ggplot2)
    exports2$distbin <- floor(exports2$p90dist / 10)
    exports2$distbin[exports2$distbin > 32] <- 33
    ggplot(exports2, aes(distbin, value / 1e9)) +
        geom_col() + scale_x_continuous(breaks=c(0, 10, 20, 30, 33), labels=c(0, 100, 200, 300, ">320"), name="Distance from shore (km)") + theme_bw() +
        ylab("Value crossing boundaries (billion USD)")

    sum(exports2$value[exports2$p90dist < 50], na.rm=T) / sum(exports2$value)

    plotdf1 <- results %>% group_by(sink) %>% summarize(level='species', groups=length(unique(specie[!isself])))
    plotdf2 <- results %>% group_by(sink) %>% summarize(level='genus', groups=length(unique(sapply(specie[!isself], function(ss) strsplit(as.character(ss), " ")[[1]][1]))))
    plotdf <- rbind(plotdf1, plotdf2)
    plotdf$level <- factor(plotdf$level, levels=c('species', 'genus'))
    ggplot(plotdf, aes(groups)) +
        facet_grid(level ~ .) + theme_bw() +
        geom_histogram() + xlab("EEZs with the given number of species or genuses") + ylab(NULL)
    mean(plotdf1$groups)
    mean(plotdf2$groups)

    mean((exports %>% group_by(sink) %>% summarize(sources=length(unique(source[source != as.character(sink)]))))$sources)
}

## Combine these as the total value at risk for each sink
totalrisk <- data.frame(eez=c(), value=c(), catch=c(), proteincatch=c(), sovereign=c(), resilience=c())
for (eez in unique(results$sink)) {
    subres <- subset(results, sink == eez)
    if (length(unique(subres$sovereign)) > 1) {
        print(c("Multiple sovereigns within", eez))
        next
    }

    sovereign <- unique(subres$sovereign)

    for (level in unique(subres$resilience)) {
        if (do.drophighres && level == 'high')
            next
        ssrr <- subset(subres, resilience == level)
        value <- sum(ssrr$value * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)
        catch <- sum(ssrr$catch * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)
        proteincatch <- sum(ssrr$protein * ssrr$catch * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)

        totalrisk <- rbind(totalrisk, data.frame(sink=eez, value, catch, proteincatch, sovereign, resilience=level))
    }

    if (do.drophighres) {
        ssrr <- subset(subres, resilience != 'high')
        value <- sum(ssrr$value * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)
        catch <- sum(ssrr$catch * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)
        proteincatch <- sum(ssrr$protein * ssrr$catch * (ssrr$totalportion - ssrr$selfportion) / ssrr$totalportion, na.rm=T)
    } else {
        value <- sum(subres$value * (subres$totalportion - subres$selfportion) / subres$totalportion, na.rm=T)
        catch <- sum(subres$catch * (subres$totalportion - subres$selfportion) / subres$totalportion, na.rm=T)
        proteincatch <- sum(subres$protein * subres$catch * (subres$totalportion - subres$selfportion) / subres$totalportion, na.rm=T)
    }
    totalrisk <- rbind(totalrisk, data.frame(sink=eez, value, catch, proteincatch, sovereign, resilience="total"))
}

if (do.drophighres) {
    write.csv(subset(totalrisk, resilience == 'total'), paste0(resultpath, "atrisk/value-nohi", outsuffix, ".csv"), row.names=F)
    write.csv(totalrisk, paste0(resultpath, "atrisk/value-nohi-split", outsuffix, ".csv"), row.names=F)
} else {
    write.csv(subset(totalrisk, resilience == 'total'), paste0(resultpath, "atrisk/value", outsuffix, ".csv"), row.names=F)
    write.csv(totalrisk, paste0(resultpath, "atrisk/value-split", outsuffix, ".csv"), row.names=F)
}

## Group exports by sovereign
eezexports <- data.frame(eez=c(), value=c(), catch=c(), resilience=c())
for (eez in unique(exports$source)) {
    subres <- subset(exports, source == eez & !isself)

    for (level in unique(subres$resilience)) {
        if (do.drophighres && level == 'high')
            next
        eezexports <- rbind(eezexports, data.frame(eez, resilience=level,
                                                   value=sum(subres$value[subres$resilience == level], na.rm=T),
                                                   catch=sum(subres$catch[subres$resilience == level], na.rm=T)))
    }

    eezexports <- rbind(eezexports, data.frame(eez, resilience='total', value=sum(subres$value, na.rm=T), catch=sum(subres$catch, na.rm=T)))
}

if (do.figures) {
    ## Plot the total value at risk
    library(ggplot2)

    totalrisk$sink <- factor(totalrisk$sink, levels=totalrisk$sink[totalrisk$resilience == 'total'][order(totalrisk$value[totalrisk$resilience == 'total'])])

    pdf(paste0(resultpath, "atrisk-value-split", outsuffix, ".pdf"), width=3.5, height=4)
    ggplot(subset(totalrisk, resilience != 'total' & sink %in% rev(levels(totalrisk$sink))[1:20]), aes(x=sink, y=value, fill=resilience)) +
        geom_bar(stat="identity") + coord_flip() + ylab("Value imported (USD)") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total value imported from other regions") +
        scale_fill_discrete(name="Resilience:") + theme(legend.position=c(1, 0), legend.justification=c(1, 0))
    dev.off()

    ## Plot the total catch at risk
    totalrisk$sink <- factor(totalrisk$sink, levels=totalrisk$sink[totalrisk$resilience == 'total'][order(totalrisk$catch[totalrisk$resilience == 'total'])])

    pdf(paste0(resultpath, "atrisk-catch-split", outsuffix, ".pdf"), width=4, height=4)
    ggplot(subset(totalrisk, resilience != 'total' & sink %in% rev(levels(totalrisk$sink))[1:20]), aes(x=sink, y=catch, fill=resilience)) +
        geom_bar(stat="identity") + coord_flip() + ylab("Catch imported (MT)") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total catch imported from other regions") +
        scale_fill_discrete(name="Resilience:") + theme(legend.position=c(1, 0), legend.justification=c(1, 0))
    dev.off()

    ## Combined, sorted by value
    comborisk <- totalrisk[, c('resilience', 'sink', 'catch')]
    names(comborisk) <- c('resilience', 'sink', 'value')
    comborisk$metric <- "Catch imported (MT)"
    comborisk <- rbind(comborisk, cbind(totalrisk[, c('resilience', 'sink', 'value')], data.frame(metric="Value imported (USD)")))

    comborisk$sink <- factor(comborisk$sink, levels=totalrisk$sink[totalrisk$resilience == 'total'][order(totalrisk$catch[totalrisk$resilience == 'total'])])

    buffing <- data.frame(metric=c("Catch imported (MT)", "Value imported (USD)"), sink=rep("China", 2), value=c(max(max(totalrisk$catch[totalrisk$resilience == 'total']), max(eezexports$catch[eezexports$resilience == 'total'])), max(max(totalrisk$value[totalrisk$resilience == 'total']), max(eezexports$value[eezexports$resilience == 'total']))) - c(totalrisk$catch[totalrisk$resilience == 'total' & totalrisk$sink == 'China'], totalrisk$value[totalrisk$resilience == 'total' & totalrisk$sink == 'China']), resilience='blank')

    pcomborisk <- rbind(subset(comborisk, resilience != 'total' & sink %in% rev(levels(comborisk$sink))[1:20]), buffing)
    pcomborisk$resilience <- factor(pcomborisk$resilience, c("blank", "high", "medium", "low", "very low"))

    pdf(paste0(resultpath, "atrisk-combo-split", outsuffix, ".pdf"), width=6, height=3.5)
    ggplot(pcomborisk, aes(x=sink, y=value, fill=resilience)) +
        facet_grid(. ~ metric, scales="free") +
        geom_bar(stat="identity") + coord_flip() + ylab("Value (USD) or Catch (MT) imported") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total value imported from other regions") +
        scale_fill_manual(name="Resilience:", breaks=c("blank", "high", "medium", "low", "very low"), values=c('#ffffff', '#fff7bc', '#fec44f', '#d95f0e', '#d95f0e'), labels=c("REMOVE", "High (> 99%)", "Medium (> 95%)", "Low (< 95%)", "Low (< 95%)")) + theme_minimal()
    dev.off()
}

if (do.figures) {
    ## Plot the total exports
    eezexports$eez <- factor(eezexports$eez, levels=eezexports$eez[eezexports$resilience == 'total'][order(eezexports$value[eezexports$resilience == 'total'])])

    pdf(paste0(resultpath, "export-value-split", outsuffix, ".pdf"), width=3.5, height=4)
    ggplot(subset(eezexports, resilience != 'total' & eez %in% rev(levels(eezexports$eez))[1:20]), aes(x=eez, y=value, fill=resilience)) +
        geom_bar(stat="identity") + coord_flip() + ylab("Value exported (USD)") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total value exported to other regions") +
        scale_fill_discrete(name="Resilience:") + theme(legend.position=c(1, 0), legend.justification=c(1, 0))
    dev.off()

    ## Plot the total exported catch
    eezexports$eez <- factor(eezexports$eez, levels=eezexports$eez[eezexports$resilience == 'total'][order(eezexports$catch[eezexports$resilience == 'total'])])

    pdf(paste0(resultpath, "export-catch-split", outsuffix, ".pdf"), width=4, height=4)
    ggplot(subset(eezexports, resilience != 'total' & eez %in% rev(levels(eezexports$eez))[1:20]), aes(x=eez, y=catch, fill=resilience)) +
        geom_bar(stat="identity") + coord_flip() + ylab("Catch exported (MT)") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total catch exported to other regions") +
        scale_fill_discrete(name="Resilience:") + theme(legend.position=c(1, 0), legend.justification=c(1, 0))
    dev.off()

    ## Combined, sorted by value
    comboexports <- eezexports[, c('resilience', 'eez', 'catch')]
    names(comboexports) <- c('resilience', 'eez', 'value')
    comboexports$metric <- "Catch exported (MT)"
    comboexports <- rbind(comboexports, cbind(eezexports[, c('resilience', 'eez', 'value')], data.frame(metric="Value exported (USD)")))

    comboexports$eez <- as.character(comboexports$eez)
    comboexports$eez[comboexports$eez == "Howland Island and Baker Island"] <- "Howland & Baker Islands"
    comboexports$eez <- factor(comboexports$eez, levels=eezexports$eez[eezexports$resilience == 'total'][order(eezexports$catch[eezexports$resilience == 'total'])])

    pdf(paste0(resultpath, "export-combo-split", outsuffix, ".pdf"), width=6, height=3.5)
    ggplot(subset(comboexports, resilience != 'total' & eez %in% rev(levels(comboexports$eez))[1:20]), aes(x=eez, y=value, fill=resilience)) +
        facet_grid(. ~ metric, scales="free") +
        geom_bar(stat="identity") + coord_flip() + ylab("Value (USD) or Catch (MT) exported") + xlab("EEZ") +
        scale_y_continuous(expand=c(0, 0)) + ggtitle("Total value exported to other regions") +
        scale_fill_manual(name="Resilience:", breaks=c("high", "medium", "low", "very low"), values=c('#fff7bc', '#fec44f', '#d95f0e', '#d95f0e'), labels=c("High (> 99%)", "Medium (> 95%)", "Low (< 95%)", "Low (< 95%)")) + theme_minimal()
    dev.off()
}

source("../food/mastertable.R")
source("../food/calc_food_weights.R")

## Weight by %GDP or inc p.c. - food weight as calculated in codeR/food/calc_food_weights.R
totalrisk.country <- data.frame(sovereign=c(), value=c(), byecon=c(), bygdp=c(), byjobs=c(), byfood=c(), resilience=c())
for (ii in 1:nrow(weights)) {
    if (is.na(weights$sovereign[ii]))
        next
    tis <- totalrisk$sovereign == as.character(weights$sovereign[ii])
    if (sum(tis) == 0) {
        totalrisk.country <- rbind(totalrisk.country, data.frame(sovereign=weights$sovereign[ii], value=0, catch=0, byecon=0, bygdp=0, byjobs=0, byfood=0, resilience='total')) #bypro=((0/weights$avgcatch[ii])*weights$protein.ratio[ii]), byapro=(0/weights$avgcatch[ii])*weights$protein.an.ratio[ii]))
        next
    }
    value <- c()
    catch <- c()
    proteincatch <- c()
    for (level in unique(totalrisk$resilience[tis])) {
        value <- c(value, sum(totalrisk$value[tis & totalrisk$resilience == level], na.rm=T))
        catch <- c(catch, sum(totalrisk$catch[tis & totalrisk$resilience == level], na.rm=T))
        proteincatch <- c(proteincatch, sum(totalrisk$catch[tis & totalrisk$resilience == level], na.rm=T))
    }

    food.table <- calc.food.table(weights$sovereign[ii], 2014 + fromyear, 2014 + toyear)
    food.metric <- calc.food.metric(food.table, weights$avgcatch[ii], 48, weights$protein.pc[ii], weights$protein.ff[ii], proteincatch / weights$avgproteincatch[ii])

    totalrisk.country <- rbind(totalrisk.country, data.frame(sovereign=weights$sovereign[ii], value, catch, byecon=value / weights$avgecon[ii], bygdp=value / weights$gdp[ii], byjobs=(value / weights$avgecon[ii]) * weights$workers[ii] / weights$laborforce[ii], byfood=proteincatch / weights$avgproteincatch[ii], resilience=unique(totalrisk$resilience[tis]))) #bypro=((catch/weights$avgcatch[ii])*weights$protein.ratio[ii]), byapro=(catch/weights$avgcatch[ii])*weights$protein.an.ratio[ii]))
}

## Needed these before, but now only bygdp has a value > 1 (Solomon Islands)
##totalrisk$byecon[totalrisk$byecon > 1] <- 1
##totalrisk$bygdp[totalrisk$bygdp > 1] <- 1
##totalrisk$byjobs[totalrisk$byjobs > 1] <- 1

if (do.drophighres) {
    write.csv(totalrisk.country, paste0(resultpath, "atrisk/portion-nohi-split", outsuffix, ".csv"), row.names=F)
} else {
    write.csv(totalrisk.country, paste0(resultpath, "atrisk/portion-split", outsuffix, ".csv"), row.names=F)
}

## Plot these all
## This selects the top countries by econ value to include in the plot. Needs to be done separately for food variables.
scores <- totalrisk.country$byecon[totalrisk.country$resilience == 'total'] #* totalrisk.country$bygdp * totalrisk.country$byjobs # don't do combined, because some need to be 0
included <- scores > quantile(scores, 1 - 30/sum(totalrisk.country$resilience == 'total'), na.rm=T)
included[is.na(included)] <- F
included <- totalrisk.country$sovereign %in% totalrisk.country$sovereign[totalrisk.country$resilience == 'total'][included]

alltotals <- data.frame(sovereign=rep(totalrisk.country$sovereign[included], 4), metric=rep(c("By fishery value", "By GDP", "By jobs", "By protein"), each=sum(included)), values=c(totalrisk.country$byecon[included], totalrisk.country$bygdp[included], totalrisk.country$byjobs[included], totalrisk.country$byfood[included]), resilience=rep(totalrisk.country$resilience[included], 4))

if (do.figures) {
    alltotals$sovereign <- factor(alltotals$sovereign, levels=totalrisk.country$sovereign[totalrisk.country$resilience == 'total'][order(totalrisk.country$byecon[totalrisk.country$resilience == 'total'])])

    library(scales)
    library(grid)

    bycatch <- "#007EA5"
    byfood <- "#FF6600"
    bygdp <- "#669900"
    byjobs <- "#000066"

    if (do.drophighres)
        pdf(paste0(resultpath, "atrisk-portion-nohi-split", outsuffix, ".pdf"), width=8, height=5)
    else
        pdf(paste0(resultpath, "atrisk-portion-split", outsuffix, ".pdf"), width=8, height=5)
    ggplot(subset(alltotals, resilience != 'total'), aes(x=sovereign, y=values, fill=resilience)) +
        facet_grid(. ~ metric) +
        geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
        scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, 1), oob=squish) + ggtitle("Fraction of the benefit from fisheries at risk.") +
        theme(legend.position="top", panel.margin = unit(2, "lines")) +
        scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
    dev.off()

    if (do.drophighres) {
        pdf(paste0(resultpath, "atrisk-portion-nohi-100-split", outsuffix, ".pdf"), width=3.4, height=5)
        ggplot(subset(alltotals, resilience != 'total' & metric == "By fishery value"), aes(x=sovereign, y=values, fill=resilience)) +
            facet_grid(. ~ metric) +
            geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
            scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, 1), oob=squish) + ggtitle("Fraction of the benefit at risk.") +
            theme(legend.position="top", panel.margin = unit(2, "lines")) +
            scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
        dev.off()

        pdf(paste0(resultpath, "atrisk-portion-nohi-20-split", outsuffix, ".pdf"), width=3.4, height=5)
        ggplot(subset(alltotals, resilience != 'total' & metric == "By jobs"), aes(x=sovereign, y=values, fill=resilience)) +
            facet_grid(. ~ metric) +
            geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
            scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, .2), oob=squish) + ggtitle("Fraction of the benefit at risk.") +
            theme(legend.position="top", panel.margin = unit(2, "lines")) +
            scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
        dev.off()

        pdf(paste0(resultpath, "atrisk-portion-nohi-5-split", outsuffix, ".pdf"), width=5, height=5)
        ggplot(subset(alltotals, (resilience != 'total' & metric == "By GDP") | (resilience == 'total' & metric == "By protein")), aes(x=sovereign, y=values, fill=resilience)) +
            facet_grid(. ~ metric) +
            geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
            scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, .05), oob=squish) + ggtitle("Fraction of the benefit at risk.") +
            theme(legend.position="top", panel.margin = unit(2, "lines")) +
            scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
        dev.off()
    } else {
        pdf(paste0(resultpath, "atrisk-portion-macros-split", outsuffix, ".pdf"), width=5, height=5)
        ggplot(subset(alltotals, resilience != 'total' & metric %in% c("By fishery value", "By GDP")), aes(x=sovereign, y=values, fill=resilience)) +
            facet_grid(. ~ metric) +
            geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
            scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, 1), oob=squish) + ggtitle("Fraction of the benefit at risk.") +
            theme(legend.position="top", panel.margin = unit(2, "lines")) +
            scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
        dev.off()

        pdf(paste0(resultpath, "atrisk-portion-micros-split", outsuffix, ".pdf"), width=5, height=5)
        ggplot(subset(alltotals, (resilience != 'total' & metric == "By jobs") | (resilience == 'total' & metric == "By protein")), aes(x=sovereign, y=values, fill=resilience)) +
            facet_grid(. ~ metric) +
            geom_bar(stat="identity") + coord_flip() + ylab("Fishery value at risk") + xlab("Country") +
            scale_y_continuous(expand=c(0, 0), labels=percent, limits=c(0, .2), oob=squish) + ggtitle("Fraction of the benefit at risk.") +
            theme(legend.position="top", panel.margin = unit(2, "lines")) +
            scale_fill_discrete(name=NULL) + theme(legend.position=c(-.5, 1.5), legend.justification=c(-.5, 1.5))
        dev.off()
    }
}


