do.windows <- .Platform$OS.type != "unix"
if (do.windows){
  setwd("C:/Users/Nandini/Dropbox/High_Seas/codeR")
  datapath <- "C:/Users/Nandini/OneDrive/Columbia/Research/Conflict hotspots/highseas/"
} else {
  setwd("~/Dropbox/High_Seas/codeR")
  #datapath <- "~/research/highseas/"
  datapath <- "~/Documents/highseas/"
}

currents <- "-aa" #"-cl"
sensitivity <- "-30pshorter" # "" "-halfreturn"

spawn.suffix <- paste0(currents,sensitivity)

source("saufuncs.R")

## Species-specific economic values
values <- read.delim(paste0(datapath, "dataTEXT/saudata-new/values.csv"), sep=",", header=F)

## Species-specific catches
catches <- read.delim(paste0(datapath, "dataTEXT/saudata-new/catches.csv"), sep=",", header=F)
#catches[,1] <- gsub("/11.aspx", ".aspx", gsub("~", "~/", catches[,1]))

## SAU and Sovereign-level weights
## Generated by country-weights.R
regions <- read.csv(paste0(datapath, "dataCSV/weights/combined-regions-new.csv"))
#weights <- read.csv(paste0(datapath, "dataCSV/weights/combined-country-temp-nr.csv"))
groups <- read.csv(paste0(datapath, "dataTEXT/saudata-new/species.csv"))

## EEZ to EEZ transitions
## Generated by transitions/analysis.R
transits <- read.csv(paste0(paste0(datapath, "dataCSV/spawn-transits/spawn-transits-rescaled", spawn.suffix, ".csv")))
#The original file is spawn-transits-rescaled-shelf-cl-new.
#Uncertainty tests produce spawn-transits-rescaled-shelf-cl-new-30pshorter and spawn-transits-rescaled-shelf-cl-new-halfreturn
#A new edgeweights file needs to be generated separately for each of these.

results <- data.frame(sink=c(), source=c(), value=c(), catch=c())
resspecies <- data.frame(source=c(), sink=c(), species=c())
for (eezsi in unique(transits$sink)) {
  insau <- regions$name %in% eez2sau(eezsi)
  regionids <- regions$country[insau]
  eeznum <- as.numeric(substring(regionids, 7, nchar(as.character(regionids)) - 5))
  myvalues <- combine.regions(values, regionids)
  mycatches <- combine.regions(catches, regionids)
  mygroups <- subset(groups, eez %in% eeznum)

  for(eezso in unique(transits$source)) {
    thistransit <- transits[transits$source == eezso & transits$sink == eezsi,]
    e_ij_value <- 0
    e_ij_catch <- 0
    e_ij_value_denom <- 0
    e_ij_catch_denom <- 0
    e_ij_species <- c()
    e_ij_byspecies <- c()
    if (nrow(thistransit)==0){
      next
    }

    ## Look for species not in SAU, and group to genus
    thistransit$insau <- thistransit$species %in% mygroups$scientific
    thistransit$genus <- sapply(strsplit(as.character(thistransit$species), " "), function(x) x[1])
    newtransit <- subset(thistransit, insau)
    for (genus in unique(thistransit$genus)) {
        portion <- mean(thistransit$portion[thistransit$genus == genus], na.rm=T)
        newtransit <- rbind(newtransit, data.frame(source=eezso, sink=eezsi, portion, species=genus, insau=NA, genus))
    }

    count <- 0
    for(row in 1:nrow(newtransit)) {
        if (is.na(newtransit$portion[row]))
            next

        valuecatch <- species.averages.keyed(as.character(newtransit$species[row]),mygroups,myvalues,mycatches)

        spvalue <- valuecatch[1]
        spcatch <- valuecatch[2]

        if (is.na(spvalue))
            spvalue <- 0
        if (is.na(spcatch))
            spcatch <- 0

        if (spvalue > 0)
            count <- count + 1

        e_ij_value <- e_ij_value+(spvalue*newtransit$portion[row])
        e_ij_catch <- e_ij_catch+(spcatch*newtransit$portion[row])
        e_ij_value_denom <- e_ij_value_denom+spvalue
        e_ij_catch_denom <- e_ij_catch_denom+spcatch
        e_ij_species <- c(e_ij_species, as.character(newtransit$species[row]))
        e_ij_byspecies <- c(e_ij_byspecies, spcatch*newtransit$portion[row])
    }
    print(c(eezso, eezsi, count))

    results <- rbind(results,data.frame(source=eezso,sink=eezsi,value=e_ij_value,catch=e_ij_catch,catchavg=e_ij_catch/e_ij_catch_denom, valueavg=e_ij_value/e_ij_value_denom))
    if (length(e_ij_species) > 0)
        resspecies <- rbind(resspecies, data.frame(source=eezso,sink=eezsi,species=e_ij_species,portion=e_ij_byspecies / e_ij_catch_denom))
  }
}

outfile <- paste0("edgeweights",spawn.suffix,".csv")
write.csv(results,outfile,row.names=F)

write.csv(resspecies, paste0("edgecontribs", spawn.suffix, ".csv"), row.names=F)
